services:
   database:
      image: mongo
      container_name: comic-mongo
      ports:
         - 27017:27017
      networks:
         - app-network
   redis:
      image: redis
      container_name: comic-redis
      ports:
         - 6379:6379
      networks:
         - app-network
networks:
   app-network:
      driver: bridge
