version: "3"
services:
   # client:
   #    build:
   #       context: ./comic-client
   #       dockerfile: Dockerfile
   #    env_file:
   #       - ./comic-client/.env
   #    ports:
   #       - 3000:3000
   #    networks:
   #       - app-network

   server:
      build:
         context: ./comic-api
         dockerfile: Dockerfile
      env_file:
         - ./comic-api/.env
      ports:
         - 5000:5000
      depends_on:
         - database
         - redis
      networks:
         - app-network

   database:
      image: mongo
      container_name: comic-mongo
      ports:
         - 27017:27017
      volumes:
         - ./mongodb:/data/db
      networks:
         - app-network

   redis:
      image: redis
      container_name: comic-redis
      ports:
         - 6379:6379
      volumes:
         - ./redisdb:/data
      networks:
         - app-network

   nginx:
      image: nginx:1.23.3
      ports:
         - 80:80
      volumes:
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - server
         # - client
      networks:
         - app-network

networks:
   app-network:
      driver: bridge
