import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import HolyLoader from "holy-loader";
import "~/styles/globals.css";
import { cn } from "~/lib/utils";

const font = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Comic app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "bg-background text-text")}>
        <HolyLoader color="var(--primary-color)" height="2px" easing="linear" />
        {children}
      </body>
    </html>
  );
}
